# Use root/example as user/password credentials
version: '3.1'

services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
    ports:
      - 3306:3306
